
### Create Link Request
POST http://localhost:3001/api/create-link
Content-Type: application/json
api-key: akjf75Yk34GjhfdsAGDVDHyg

{
  "link": "https://sports.yahoo.com/arkansas-comes-back-from-11-point-deficit-to-upset-no-4-tennessee-032557609.html"
}

###
