"use client"
import { useEffect, useState } from 'react';
import Head from 'next/head';

const HashPage = () => {
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    const getHash = async () => {
      const hash = window.location.pathname.split('/')[1];
      const res = await fetch(`/api/hash/${hash}`);
      const data = await res.json();

      if (res.status === 200 && data.link) {
        window.location.href = data.link;
      } else if (res.status === 404) {
        setNotFound(true);
      }
    };

    getHash();
  }, []);

  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../favicon.ico" />
      </Head>
      {notFound && <h1>Requested link not found</h1>}
    </div>
  );
};

export default HashPage;
